name: rotation_stage
description: A four-sided stage for representing 3D objects with four widgets
version: 0.1.0
homepage: https://www.fyzo.de
repository: https://github.com/fyzo-dev/rotation_stage
issue_tracker: https://github.com/fyzo-dev/rotation_stage/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.1.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
